[build]
publish = "dist"
command = "npm run build"

[build.environment]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/api/*"
to = "https://flexai-7hd4.onrender.com/:splat"
status = 200
force = true
